### ISSUE TITLE
What should be the Epoch value ? 

### ISSUE THREAD

**Issue by imerkle** [blitzstudios/snowflake#2]
What range should epoch value be in ? or it should be the standard epoch of time when server will be started ?

And why higher epoch produces lower id 
and lower epoch produces higher id  ?

**Comment by weixiyen** [comment]
Epoch just needs to come anytime before your first ID is generated.  A good one might be "launch day" for your app.

If the epoch is higher, the ID is lower because it starts counting from a later time.

A lower epoch means more time has elapsed since epoch, and that time elapsed is the timestamp used for the ID, which produces a higher ID.
